name: .NET CI test and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: check path
      run: pwd
    - name: Restore dependencies
      run: dotnet restore ./FrontendBFF
    - name: Build
      run: dotnet build --no-restore ./FrontendBFF 
    - name: Test
      run: dotnet test --no-build --verbosity normal ./FrontendBFF
